#!/usr/bin/env bash
# Wrapper script to call Ollama-based news agent and create GitHub issues
set -euo pipefail

# Required environment variables
: "${OLLAMA_URL:?OLLAMA_URL must be set}"
: "${OLLAMA_MODEL:?OLLAMA_MODEL must be set}"
: "${SITE_URL:?SITE_URL must be set}"
: "${GITHUB_REPOSITORY:?GITHUB_REPOSITORY must be set}"

# News sources for this batch (can be overridden)
if [ -z "${NEWS_SOURCES:-}" ]; then
  SOURCES=(
    "https://www.reuters.com/"
    "https://apnews.com/"
    "https://www.bbc.com/news"
    "https://www.al-monitor.com/"
  )
else
  IFS=',' read -ra SOURCES <<< "$NEWS_SOURCES"
fi

echo "=== Ollama News Agent ==="
echo "Ollama URL: $OLLAMA_URL"
echo "Model: $OLLAMA_MODEL"
echo "Sources: ${#SOURCES[@]}"

# Check dependencies
for cmd in curl jq gh; do
  if ! command -v "$cmd" &> /dev/null; then
    echo "Error: $cmd is not installed" >&2
    exit 1
  fi
done

# Test Ollama connection
echo "Testing Ollama connection..."
if ! curl -sf "$OLLAMA_URL/api/tags" > /dev/null; then
  echo "Error: Cannot connect to Ollama at $OLLAMA_URL" >&2
  exit 1
fi

echo "Fetching existing events for deduplication..."
EXISTING_EVENTS=$(curl -sf "${SITE_URL}/api/events/recent?hours=12" | jq -r '.[] | "\(.timeET) | \(.headline)"' 2>/dev/null || echo "")
PENDING_ISSUES=$(gh issue list --repo "${GITHUB_REPOSITORY}" --label "pending-review" --state open --limit 100 --json title -q '.[].title' 2>/dev/null || echo "")

echo "Scraping news sources..."
RAW_NEWS=""
for url in "${SOURCES[@]}"; do
  echo "  Fetching $url..."
  content=$(curl -sfL --max-time 30 "$url" 2>/dev/null | head -c 15000 || echo "Failed to fetch")
  RAW_NEWS+="=== $url ===\n${content}\n\n"
done

# Build prompt
read -r -d '' PROMPT <<EOF || true
You are a news aggregation agent for Operation Epic Fury (US-Israel strikes on Iran, Feb 28 2026).

EXISTING EVENTS (do not duplicate):
${EXISTING_EVENTS}

PENDING ISSUES (do not duplicate):
${PENDING_ISSUES}

Analyze the following news sources and extract NEW military/diplomatic developments about Operation Epic Fury.

CRITICAL: Output ONLY a valid JSON array. No markdown, no explanations, just JSON.

Format:
[
  {
    "title": "Brief headline",
    "description": "2-3 sentence summary",
    "timestamp": "ISO 8601 timestamp",
    "confidence": "confirmed",
    "sources": [{"name": "Reuters", "url": "https://..."}],
    "sourceRegion": "us",
    "location": {"name": "Tehran, Iran", "lat": 35.6892, "lng": 51.3890}
  }
]

Only include events from the last 24 hours. If no new events, return empty array [].

NEWS CONTENT:
$(echo -e "$RAW_NEWS")
EOF

echo "Calling Ollama for analysis..."
PROMPT_JSON=$(echo "$PROMPT" | jq -Rs .)
RESPONSE=$(curl -sf "$OLLAMA_URL/api/generate" \
  -H "Content-Type: application/json" \
  -d "{\"model\": \"$OLLAMA_MODEL\", \"prompt\": $PROMPT_JSON, \"stream\": false, \"options\": {\"temperature\": 0.3}}" \
  | jq -r '.response' 2>/dev/null)

if [ -z "$RESPONSE" ]; then
  echo "Error: Empty response from Ollama" >&2
  exit 1
fi

echo "Parsing events..."
# Try to extract JSON from response (handle markdown wrapping)
if echo "$RESPONSE" | grep -q '```json'; then
  EVENTS=$(echo "$RESPONSE" | sed -n '/```json/,/```/p' | sed '1d;$d')
else
  EVENTS="$RESPONSE"
fi

# Validate JSON
if ! echo "$EVENTS" | jq empty 2>/dev/null; then
  echo "Error: Invalid JSON response from Ollama" >&2
  echo "Response: $RESPONSE" >&2
  exit 1
fi

# Check if empty array
EVENT_COUNT=$(echo "$EVENTS" | jq 'length')
if [ "$EVENT_COUNT" -eq 0 ]; then
  echo "No new events found."
  exit 0
fi

echo "Found $EVENT_COUNT new event(s). Creating GitHub issues..."

# Create issues
echo "$EVENTS" | jq -c '.[]' | while IFS= read -r event; do
  TITLE=$(echo "$event" | jq -r '.title')
  DESCRIPTION=$(echo "$event" | jq -r '.description')
  CONFIDENCE=$(echo "$event" | jq -r '.confidence // "unconfirmed"')
  
  if [ -z "$TITLE" ] || [ "$TITLE" = "null" ]; then
    echo "  Skipping event with missing title" >&2
    continue
  fi
  
  echo "  Creating issue: $TITLE"
  
  ISSUE_BODY="$DESCRIPTION

**Event Data:**
\`\`\`json
$event
\`\`\`

---
*Generated by Ollama news agent*"
  
  if ! gh issue create \
    --repo "${GITHUB_REPOSITORY}" \
    --title "$TITLE" \
    --label "pending-review,auto-news,$CONFIDENCE" \
    --body "$ISSUE_BODY" 2>&1; then
    echo "  Warning: Failed to create issue for: $TITLE" >&2
  fi
done

echo "Done! Created $EVENT_COUNT issue(s)."
